# Unique identifier of the project on SonarCloud
sonar.projectKey=Flirnz_Devops_project

# Organization key on SonarCloud
sonar.organization=flirnz

# Path to the source directories
sonar.sources=backend/src,frontend/src

# Path to the test directories
sonar.tests=backend/src/tests

# Exclude dependencies and build output from analysis
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,backend/src/tests/**

# Path to Jest coverage reports
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info

# Exclude frontend from coverage calculation since there are no frontend tests
sonar.coverage.exclusions=frontend/src/**

