apiVersion: v1
kind: Secret
metadata:
  name: thinkboard-secrets
type: Opaque
stringData:
  upstash-redis-url: {{ .Values.upstash.redisUrl | quote }}
  upstash-redis-token: {{ .Values.upstash.redisToken | quote }}
