name: Continuous Integration

on:
  push:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0

      - name: Run a one-line script
        run: echo "Foundation Pipeline Success"

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 20

      - name: Confirmation message
        run: node -v

      - name: Install Backend Dependencies
        run: npm install
        working-directory: "./backend"

      - name: Run Backend Linter
        run: npm run lint
        working-directory: "./backend"

      - name: Run Backend Tests
        run: npm test -- --coverage
        working-directory: "./backend"

      - name: Install Frontend Dependencies
        run: npm install
        working-directory: "./frontend"

      - name: Run Frontend Linter
        run: npm run lint
        working-directory: "./frontend"

      - name: Build Frontend
        run: npm run build
        working-directory: "./frontend"

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@c7ee0f9df90b7aa20e8dcf9695dcfe2e7da5b4f2 # v7
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Build Backend Docker Image
        run: docker build -t thinkboard-backend:${{ github.sha }} ./backend

      - name: Build Frontend Docker Image
        run: docker build -t thinkboard-frontend:${{ github.sha }} ./frontend
