name: Continuous Integration

on:
  push:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Run a one-line script
        run: echo "Foundation Pipeline Success"

      - name: Setup Node.js
        uses: actions/setup-node@39370e3970a6d050c4800ad4ff1db345512b9c3f # v4.1.0
        with:
          node-version: 20

      - name: Confirmation message
        run: node -v

      - name: Install Backend Dependencies
        run: npm install
        working-directory: "./backend"

      - name: Run Backend Linter
        run: npm run lint
        working-directory: "./backend"

      - name: Run Backend Tests
        run: npm test -- --coverage
        working-directory: "./backend"

      - name: Install Frontend Dependencies
        run: npm install
        working-directory: "./frontend"

      - name: Run Frontend Linter
        run: npm run lint
        working-directory: "./frontend"

      - name: Build Frontend
        run: npm run build
        working-directory: "./frontend"

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@299e4b793aaa83bf2aba7c9c14bedbb485688ec4 # v7.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
